baseURL: "https://marceloamancio.github.io/"
languageCode: en-us
title: Marcelo's blog 
theme: PaperMod

menu:
  main:

  #  - identifier: index 
  #    name: About 
  #    url: /
  #    weight: 5
    - identifier: cv 
      name: CV 
      url: /cv
      weight: 10
 #   - identifier: about 
 #     name: About
 #     url: /about
 #     weight: 3
 #   - identifier: cv 
 #     name: CV
 #     url: /cv
 #     weight: 10
  
 #   - identifier: categories
 #     name: Categories
 #     url: /categories/
 #     weight: 20
 #   - identifier: tags
 #     name: Tags
 #     url: /tags/
 #     weight: 30
 #   - identifier: archives 
 #     name: Archives
 #     url: /archives/
 #     weight: 40
